modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="cloucubemod"
version="1.0.0"
displayName="CloucubeMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Gala_Glow"

[[dependencies.cloucubemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




